### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#1]
After 'list' is selected, it remains selected even if another data structure is selected later on

![s1](https://cloud.githubusercontent.com/assets/21997043/18532818/4029763c-7aa4-11e6-91a0-f1414ac7a0e5.JPG)

**Comment by C0LETRA1N** [comment]
Looking into this bug

**Comment by C0LETRA1N** [comment]
Sent pull request

**Comment by FOSSLGYS** [comment]
Feedback submitted.

**Comment by C0LETRA1N** [comment]
Modified and sent a new pull request

**Comment by FOSSLGYS** [comment]
Thank you for the update.
