### ISSUE TITLE
 Stack - Remove on empty stack

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#10]
Clicking remove on an empty stack throws a Java exception, though it is not effecting the GUI. The exception either needs to be caught/handled correctly or prevented from happening.

**Comment by blondiebytes** [comment]
I'll work on this! 👍 I'll change the code in the Remove method in Stack.java to prevent this from happening.

**Comment by FOSSLGYS** [comment]
Thank you for your contribution!
