### ISSUE TITLE
 Stack - Inconsistent Display

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#12]
For stack visualization, all values (except the top value) are misaligned. We need to push the remaining values ahead by 'n' spaces to make it align with the top value.

![p2](https://cloud.githubusercontent.com/assets/21997043/18536724/193a1d08-7ac5-11e6-85d9-11597844a8dd.png)

**Comment by C0LETRA1N** [comment]
Sent pull request
