### ISSUE TITLE
 Remove 'remove' text field

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#15]
Remove text field from view (currently disabled) from Stack, Queue and Heap data structure.

![p3](https://cloud.githubusercontent.com/assets/21997043/18536756/6dc5c0e8-7ac5-11e6-81aa-a7e4c924fdb0.png)

**Comment by C0LETRA1N** [comment]
C0LE_TRA1N_ is working on this one.

**Comment by C0LETRA1N** [comment]
Sent pull request

**Comment by FOSSLGYS** [comment]
Thank you for the update.
