### ISSUE TITLE
 Input Validation - Integer 

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#3]
The input fields expect an integer, however no checks are in place to ensure that. If the user enters a string the program throws an exception. Proper exception handling is required at the back end (formal or informal). And the user should be provided feedback if he/she enters invalid input.

**Comment by alanefl** [comment]
I intend to fix this by throwing an IllegalArgumentException if the user enters a string which is not an integer, which will print useful feedback to the user. I plan to add two checks for integer parsing in the project.  The first in the jButtonRemoveActionPerformed method, and the second in the jButtonAddActionPerformed method.  These are the only instances of Integer.parseInt on the entire project.

**Comment by alanefl** [comment]
Now that I think about it, it's probably better to instead catch a NumberFormatException then print a useful message to the user in the GUI itself.

**Comment by FOSSLGYS** [comment]
Thank you for your contribution. We reviewed your update and provided feedback, and I just looked at your comment, we had suggested the same :-)
Please update the submission.

**Comment by FOSSLGYS** [comment]
Thank you for the update.
