### ISSUE TITLE
 DS Selector - Default Selection

### ISSUE THREAD

**Issue by FOSSLGYS** [FOSSLGYS/DataVisualizer-JAVA#7]
When DS Selector opens up, it should have Stack radio button pre-selected. It appears that the behind the scene functionality is already implemented as if you hit Next without selecting anything, Stack visualization appears on the next frame. We need to explicitly make it selected for visual correctness.

![s2](https://cloud.githubusercontent.com/assets/21997043/18532958/2a5cc7a4-7aa5-11e6-8636-2b0a37908d88.png)

**Comment by C0LETRA1N** [comment]
Pull request submitted
